# NTN Stack 監控系統安全認證配置
# Security Authentication Configuration for NTN Stack Monitoring

# Grafana 安全配置
grafana:
  security:
    # 管理員認證
    admin_user: "ntn_admin"
    admin_password_env: "GRAFANA_ADMIN_PASSWORD"
    
    # OAuth 配置 (可選)
    oauth:
      enabled: true
      provider: "generic_oauth"
      client_id_env: "OAUTH_CLIENT_ID"
      client_secret_env: "OAUTH_CLIENT_SECRET"
      auth_url: "https://auth.company.com/oauth/authorize"
      token_url: "https://auth.company.com/oauth/token"
      api_url: "https://auth.company.com/oauth/userinfo"
      allowed_organizations: ["ntn-team", "operations-team"]
    
    # HTTPS/TLS 配置
    tls:
      cert_file: "/etc/ssl/certs/grafana.crt"
      key_file: "/etc/ssl/private/grafana.key"
      
    # 角色權限控制 (RBAC)
    rbac:
      roles:
        - name: "ai_team_viewer"
          permissions:
            - "dashboards:read"
            - "datasources:read"
            - "alerts:read"
          scope: "ai_decision_*"
          
        - name: "operations_admin"
          permissions:
            - "dashboards:*"
            - "datasources:*"
            - "alerts:*"
            - "users:*"
          scope: "*"
          
        - name: "emergency_responder"
          permissions:
            - "dashboards:read"
            - "alerts:write"
            - "annotations:write"
          scope: "emergency_*"

# Prometheus 安全配置
prometheus:
  security:
    # Web UI 基本認證
    basic_auth:
      enabled: true
      username: "prometheus_admin"
      password_env: "PROMETHEUS_PASSWORD"
    
    # TLS 配置
    tls:
      cert_file: "/etc/ssl/certs/prometheus.crt"
      key_file: "/etc/ssl/private/prometheus.key"
      
    # 訪問控制
    web:
      external_url: "https://prometheus.ntn-stack.local"
      route_prefix: "/prometheus"
      
    # scrape 目標安全配置
    scrape_configs_security:
      - job_name: "netstack-api"
        bearer_token_file: "/etc/prometheus/tokens/netstack.token"
        tls_config:
          ca_file: "/etc/ssl/certs/ca.crt"
          insecure_skip_verify: false

# AlertManager 安全配置
alertmanager:
  security:
    # Web UI 認證
    basic_auth:
      enabled: true
      username: "alert_admin"
      password_env: "ALERTMANAGER_PASSWORD"
      
    # TLS 配置
    tls:
      cert_file: "/etc/ssl/certs/alertmanager.crt"
      key_file: "/etc/ssl/private/alertmanager.key"
      
    # 通知安全配置
    notifications:
      email:
        require_tls: true
        tls_config:
          insecure_skip_verify: false
      
      slack:
        api_url_file: "/etc/alertmanager/secrets/slack_webhook"
        
      webhook:
        tls_config:
          ca_file: "/etc/ssl/certs/ca.crt"

# 網路安全配置
network_security:
  # 內部通信加密
  internal_tls:
    enabled: true
    ca_cert: "/etc/ssl/certs/ntn-ca.crt"
    
  # 防火牆規則
  firewall_rules:
    - name: "allow_prometheus"
      port: 9090
      source: ["10.0.0.0/8", "172.16.0.0/12"]
      protocol: "tcp"
      
    - name: "allow_grafana"
      port: 3000
      source: ["10.0.0.0/8", "172.16.0.0/12"]
      protocol: "tcp"
      
    - name: "allow_alertmanager"
      port: 9093
      source: ["10.0.0.0/8"]
      protocol: "tcp"

# 審計日誌配置
audit_logging:
  enabled: true
  destinations:
    - type: "file"
      path: "/var/log/ntn-stack/audit.log"
      format: "json"
      
    - type: "syslog"
      facility: "local0"
      severity: "info"
      
  events:
    - "authentication_failed"
    - "configuration_changed"
    - "alert_acknowledged"
    - "dashboard_exported"
    - "emergency_mode_triggered"

# 合規檢查配置
compliance:
  # 資料保留政策
  data_retention:
    metrics: "90d"          # 指標保留90天
    logs: "30d"             # 日誌保留30天
    alerts: "365d"          # 警報記錄保留1年
    
  # 隱私保護
  privacy:
    anonymize_ip: true      # IP位址匿名化
    mask_sensitive_data: true # 敏感資料遮罩
    
  # 備份加密
  backup_encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation_days: 90
    
  # 定期安全掃描
  security_scans:
    vulnerability_scan: "weekly"
    configuration_audit: "monthly"
    penetration_test: "quarterly"

# 監控API安全
api_security:
  # API金鑰管理
  api_keys:
    - name: "netstack_monitoring"
      permissions: ["metrics:read", "alerts:write"]
      expires: "2025-12-31"
      
    - name: "emergency_operator"
      permissions: ["emergency:*"]
      expires: "never"
      
  # 請求限制
  rate_limiting:
    requests_per_minute: 1000
    burst_size: 100
    
  # JWT 配置
  jwt:
    secret_env: "JWT_SECRET"
    expiry_hours: 24
    issuer: "ntn-stack-monitoring"