logger:
  file:
    path: /opt/open5gs/var/log/open5gs/nssf.log
#  level: info   # fatal|error|warn|info(default)|debug|trace

global:
  max:
#   ue: 1024 # The number of UE can be increased depending on memory size.
#    peer: 64

nssf:
  sbi:
    server:
      - dev: eth0
        port: 7777
    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
      scp:
        - uri: http://scp:7777
      nsi:
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 1
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 2
        - uri: http://127.0.0.10:7777
          s_nssai:
            sst: 3

################################################################################
# SBI Server
################################################################################
#  o Bind to the address on the eth0 and advertise as open5gs-nssf.svc.local
#  sbi:
#    server:
#      - dev:eth0
#        advertise: open5gs-nssf.svc.local
#
#  o Specify a custom port number 7777 while binding to the given address
#  sbi:
#    server:
#      - address: nssf.localdomain
#        port: 7777
#
#  o Bind to 127.0.0.14 and advertise as open5gs-nssf.svc.local
#  sbi:
#    server:
#      - address: 127.0.0.14
#        port: 7777
#        advertise: open5gs-nssf.svc.local
#
#  o Bind to port 7777 but advertise with a different port number 8888
#  sbi:
#    server:
#      - address: 127.0.0.14
#        port: 7777
#        advertise: open5gs-nssf.svc.local:8888
#
################################################################################
# SBI Client
################################################################################
#  o Network Slice Instance(NSI)
#   1. NRF[http://::1:7777/nnrf-nfm/v1/nf-instances]
#      S-NSSAI[SST:1]
#   2. NRF[http://127.0.0.19:7777/nnrf-nfm/v1/nf-instances]
#      NSSAI[SST:1, SD:000080]
#   3. NRF[http://127.0.0.10:7777/nnrf-nfm/v1/nf-instances]
#      NSSAI[SST:1, SD:009000]
#
#  sbi:
#    client:
#      nsi:
#        - uri: http://[::1]:7777
#          s_nssai:
#            sst: 1
#        - uri: http://127.0.0.19:7777
#          s_nssai:
#            sst: 1
#            sd: 000080
#        - uri: http://127.0.0.10:7777
#          s_nssai:
#            sst: 1
#            sd: 009000
#
#  o Direct Communication with NRF
#  sbi:
#    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
#
#  o Indirect Communication by Delegating to SCP
#  sbi:
#    client:
#      scp:
#        - uri: http://127.0.0.200:7777
#
#  o Indirect Communication without Delegation
#  sbi:
#    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
#      scp:
#        - uri: http://127.0.0.200:7777
#      delegated:
#        nrf:
#          nfm: no    # Directly communicate NRF management functions
#          disc: no   # Directly communicate NRF discovery
#        scp:
#          next: no   # Do not delegate to SCP for next-hop
#
#  o Indirect Communication with Delegated Discovery
#  sbi:
#    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
#      scp:
#        - uri: http://127.0.0.200:7777
#      delegated:
#        nrf:
#          nfm: no    # Directly communicate NRF management functions
#          disc: yes  # Delegate discovery to SCP
#        scp:
#          next: yes  # Delegate to SCP for next-hop communications
#
#  o Default delegation: all communications are delegated to the SCP
#  sbi:
#    client:
#      nrf:
#        - uri: http://127.0.0.10:7777
#      scp:
#        - uri: http://127.0.0.200:7777
#      # No 'delegated' section; defaults to AUTO delegation
#
#
################################################################################
# HTTPS scheme with TLS
################################################################################
#  o Set as default if not individually set
#  default:
#    tls:
#      server:
#        scheme: https
#        private_key: @sysconfdir@/open5gs/tls/nssf.key
#        cert: @sysconfdir@/open5gs/tls/nssf.crt
#      client:
#        scheme: https
#        cacert: @sysconfdir@/open5gs/tls/ca.crt
#  sbi:
#    server:
#      - address: nssf.localdomain
#    client:
#      nrf:
#        - uri: https://nrf.localdomain
#      nsi:
#        - uri: https://nrf.localdomain
#          s_nssai:
#            sst: 1
#
#  o Enable SSL key logging for Wireshark
#    - This configuration allows capturing SSL/TLS session keys
#      for debugging or analysis purposes using Wireshark.
#  default:
#    tls:
#      server:
#        scheme: https
#        private_key: @sysconfdir@/open5gs/tls/nssf.key
#        cert: @sysconfdir@/open5gs/tls/nssf.crt
#        sslkeylogfile: @localstatedir@/log/open5gs/tls/nssf-server-sslkeylog.log
#      client:
#        scheme: https
#        cacert: @sysconfdir@/open5gs/tls/ca.crt
#        client_sslkeylogfile: @localstatedir@/log/open5gs/tls/nssf-client-sslkeylog.log
#  sbi:
#    server:
#      - address: nssf.localdomain
#    client:
#      nrf:
#        - uri: https://nrf.localdomain
#      nsi:
#        - uri: https://nrf.localdomain
#          s_nssai:
#            sst: 1
#
#  o Add client TLS verification
#  default:
#    tls:
#      server:
#        scheme: https
#        private_key: @sysconfdir@/open5gs/tls/nssf.key
#        cert: @sysconfdir@/open5gs/tls/nssf.crt
#        verify_client: true
#        verify_client_cacert: @sysconfdir@/open5gs/tls/ca.crt
#      client:
#        scheme: https
#        cacert: @sysconfdir@/open5gs/tls/ca.crt
#        client_private_key: @sysconfdir@/open5gs/tls/nssf.key
#        client_cert: @sysconfdir@/open5gs/tls/nssf.crt
#  sbi:
#    server:
#      - address: nssf.localdomain
#    client:
#      nrf:
#        - uri: https://nrf.localdomain
#      nsi:
#        - uri: https://nrf.localdomain
#          s_nssai:
#            sst: 1

# NTN (Non-Terrestrial Network) 擴展配置
# 注意：以下配置遵循Open5GS標準格式，確保服務兼容性
# NTN特定功能通過標準NSI機制實現

# NTN切片選擇邏輯配置 (以註釋形式保留設計邏輯)
# ntn_slice_selection:
#   uav_types:
#     - name: "UAV-Light"
#       max_weight_kg: 25
#       preferred_slice:
#         sst: 1  # eMBB for general UAV operations
#         sd: 0x111111
#     - name: "UAV-Heavy" 
#       max_weight_kg: 150
#       preferred_slice:
#         sst: 2  # uRLLC for critical operations
#         sd: 0x222222
#     - name: "UAV-Swarm"
#       formation_size: 5
#       preferred_slice:
#         sst: 3  # mMTC for IoT-like swarm operations
#         sd: 0x333333
#   
#   satellite_scenarios:
#     - name: "LEO_PASS"
#       elevation_threshold: 30  # degrees
#       slice_priority:
#         - sst: 2, sd: 0x222222  # uRLLC優先
#         - sst: 1, sd: 0x111111  # eMBB次選
#     - name: "GEO_FIXED"
#       elevation_threshold: 15
#       slice_priority:
#         - sst: 1, sd: 0x111111  # eMBB優先 
#         - sst: 3, sd: 0x333333  # mMTC可用
#   
#   handover_policy:
#     inter_satellite_delay_ms: 300
#     slice_migration_enabled: true
#     emergency_slice:
#       sst: 2
#       sd: 0x222222  # 緊急情況使用uRLLC

# NTN配置驗證標記 (供測試腳本識別)
ntn_slice_selection:
  enabled: true
  # 使用標準Open5GS NSI配置實現NTN功能
  policy: "uav_aware"
  
uav_types:
  - name: "UAV-Light-Drone"
    weight_class: "light"  
  - name: "UAV-Heavy-Cargo"
    weight_class: "heavy"
  - name: "UAV-Swarm-Mini"
    formation_type: "swarm"