# UE-Test - 動態 Slice 切換測試用 (預設 eMBB)
supi: 'imsi-999700000000099'
mcc: '999'
mnc: '70'
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
op: 'E8ED289DEBA952E4283B54E88E6183CA'
opType: 'OPC'
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 0x111111

# gNB 連接設定 (可連接到兩個 gNB)
gnbSearchList:
  - 172.20.1.10  # gnb1 IP address (eMBB)
  - 172.20.1.20  # gnb2 IP address (uRLLC)

# 網路介面設定
tunNamePrefix: 'uesimtun'

# 日誌設定
logger:
  logLevel: 'debug' 