# UE3 - eMBB Slice (sst=1, sd=0x111111)
supi: 'imsi-999700000000003'
mcc: '999'
mnc: '70'
key: '465B5CE8B199B49FAA5F0A2EE238A6BC'
op: 'E8ED289DEBA952E4283B54E88E6183CA'
opType: 'OPC'
sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 0x111111

# gNB 連接設定
gnbSearchList:
  - 172.20.1.10  # gnb1 IP address

# 網路介面設定
tunNamePrefix: 'uesimtun'

# 日誌設定
logger:
  logLevel: 'info' 