version: '3.9'

# LEO衛星換手決策RL系統 - Docker Compose
# Phase 1: PostgreSQL真實數據儲存
#
# 這個 Docker Compose 文件定義了 RL 系統的兩個核心服務：
# 1. rl-system-api: FastAPI 應用程式，提供 RL 訓練和數據分析的接口。
# 2. rl-db: PostgreSQL 數據庫，用於持久化儲存所有實驗數據。

services:
  rl-system-api:
    build:
      context: ../..
      dockerfile: netstack/rl_system/Dockerfile
    container_name: rl_system_api
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ../..:/app
    environment:
      - ENV=docker
      - DATABASE_URL=postgresql+asyncpg://rl_user:rl_password@netstack-rl-postgres:5432/rl_research
      - RL_DATABASE_URL=postgresql://rl_user:rl_password@netstack-rl-postgres:5432/rl_research
    networks:
      - netstack-core  # 連接到 NetStack 網路

networks:
  netstack-core:
    external: true
    name: compose_netstack-core 