# Prometheus 最小化配置文件
# 階段8：最簡配置確保正常啟動

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 告警規則文件 (暫時禁用)
# rule_files:
#   - "alerts/*.yml"

# AlertManager 配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 數據抓取配置
scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter - 系統資源監控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # NTN Stack API 監控
  - job_name: 'ntn-stack-api'
    static_configs:
      - targets: ['172.17.0.1:8080']
    scrape_interval: 5s
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # AI 決策引擎專用監控
  - job_name: 'ai-decision-engine'
    static_configs:
      - targets: ['172.17.0.1:8080']
    scrape_interval: 3s
    metrics_path: '/api/v2/decision/metrics'
    scrape_timeout: 3s

  # RL 訓練監控
  - job_name: 'rl-training'
    static_configs:
      - targets: ['172.17.0.1:8080']
    scrape_interval: 5s
    metrics_path: '/api/v1/rl/metrics'
    scrape_timeout: 3s

  # Grafana 監控
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'