# Prometheus 配置文件
# 階段8：AI決策引擎監控配置

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ntn-stack'
    replica: 'prometheus-01'

# 告警規則文件
rule_files:
  - "rules/*.yml"
  - "alerts/*.yml"

# AlertManager 配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 數據抓取配置
scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter - 系統指標
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor - 容器指標
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Redis Exporter - NetStack Redis 監控
  - job_name: 'redis-netstack'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  # PostgreSQL Exporter - SimWorld 數據庫監控
  - job_name: 'postgres-simworld'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # NetStack API - AI決策引擎核心監控
  - job_name: 'netstack-api'
    static_configs:
      - targets: ['netstack-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s  # 更頻繁的監控，因為是核心服務
    scrape_timeout: 8s
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'netstack-api'
      - source_labels: [__address__]
        target_label: component
        replacement: 'ai-decision-engine'

  # NetStack API - AI決策引擎詳細指標
  - job_name: 'ai-decision-metrics'
    static_configs:
      - targets: ['netstack-api:8080']
    metrics_path: '/api/v1/ai_decision_integration/metrics'
    scrape_interval: 5s   # 高頻監控決策性能
    scrape_timeout: 4s
    params:
      detailed: ['true']
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'ai-decision-integration'
      - source_labels: [__address__]
        target_label: subsystem
        replacement: 'decision-engine'

  # NetStack API - RL訓練監控
  - job_name: 'rl-training-metrics'
    static_configs:
      - targets: ['netstack-api:8080']
    metrics_path: '/api/v1/rl/metrics'
    scrape_interval: 10s
    scrape_timeout: 8s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'rl-training'
      - source_labels: [__address__]
        target_label: component
        replacement: 'gymnasium-monitor'

  # SimWorld Backend - 模擬環境監控
  - job_name: 'simworld-backend'
    static_configs:
      - targets: ['simworld_backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'simworld-backend'
      - source_labels: [__address__]
        target_label: component
        replacement: 'simulation-engine'

  # FastAPI 應用健康監控
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'netstack-api:8080'
        - 'simworld_backend:8000'
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 5s
    relabel_configs:
      - source_labels: [__address__]
        regex: 'netstack-api:8080'
        target_label: service
        replacement: 'netstack'
      - source_labels: [__address__]
        regex: 'simworld_backend:8000'
        target_label: service
        replacement: 'simworld'

# 遠程寫入配置 (可選，用於長期存儲)
# remote_write:
#   - url: "http://prometheus-remote-storage:8080/receive"
#     queue_config:
#       max_samples_per_send: 1000
#       capacity: 10000
#       max_shards: 200

# 遠程讀取配置 (可選)
# remote_read:
#   - url: "http://prometheus-remote-storage:8080/read"