# 開發環境專用配置 - 繼承 core.yaml 並覆蓋開發相關設定
version: '3.8'

# 繼承主配置文件
include:
  - core.yaml

services:
  # NetStack API 開發環境覆蓋配置
  netstack-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        BUILD_ENV: development      # 開發模式
        INSTALL_DEV_TOOLS: true     # 安裝開發工具
    environment:
      - DATABASE_URL=mongodb://mongo:27017/open5gs
      - MONGO_HOST=mongo
      - REDIS_URL=redis://redis:6379
      - SATELLITE_DATABASE_URL=postgresql://netstack_user:netstack_password@netstack-postgres:5432/netstack_db
      - LOG_LEVEL=DEBUG             # 開發模式使用 DEBUG 級別
      - ENVIRONMENT=development     # 開發環境標記
      - PHASE0_DEV_MODE=true        # Phase 0 開發模式
      # Phase 5 容器啟動優化環境變數
      - SATELLITE_DATA_MODE=instant_load
      - POSTGRES_WAIT_TIMEOUT=30
      - PRECOMPUTE_ON_STARTUP=true
    volumes:
      - satellite_precomputed_data:/app/data
      - netstack_models:/app/models
      - netstack_results:/app/results
      - netstack_scripts:/app/scripts
      # 開發模式 - 掛載源碼以便實時編輯
      - ../netstack_api/:/app/netstack_api/:rw
      - ../src/:/app/src/:rw
    # 開發模式健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/satellite-simple/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s