deployment:
  health_check_timeout: 60
  liveness_probe_delay: 60
  readiness_probe_delay: 30
  resource_limits:
    cpu: '2.0'
    memory: 4GB
  resource_requests:
    cpu: '1.0'
    memory: 2GB
  strategy: rolling_update
phase1:
  api:
    host: 0.0.0.0
    max_connections: 100
    port: 8080
    timeout: 30
    workers: 4
  data:
    cache_size: 5000
    cache_ttl: 3600
    output_path: /app/data
    tle_data_path: /netstack/tle_data
  logging:
    backup_count: 5
    file: /app/logs/phase1.log
    format: json
    level: INFO
    max_size: 100MB
  performance:
    batch_size: 1000
    cpu_limit: '2.0'
    memory_limit: 2GB
    sgp4_threads: 8
  security:
    allowed_origins:
    - '*'
    enable_cors: true
    rate_limiting:
      requests_per_hour: 1000
      requests_per_minute: 100
